
server:
  port: 9191
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/testdatabase?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost